version: "3.3"

services:
  nginx:
    container_name: "telegram_auto_nginx"
    restart: always
    build:
      context: ./nginx
    ports:
      - $WEB_PORT:80
    depends_on:
      - web
    networks:
      - telegram_auto_net

  web:
    container_name: "telegram_auto_web"
    restart: always
    build:
      context: ./project
    volumes:
      - ./project:/usr/scr/app
    command: ./start
    ports:
      - 8000
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - telegram_auto_net

  mongo:
    image: mongo
    container_name: "telegram_auto_mongo"
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./telegram_auto_mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - telegram_auto_net

networks:
  telegram_auto_net: